### ISSUE TITLE
npm run dev on windows

### ISSUE THREAD

**Issue by paOol** [tribou/react-todo#1]
on windows 8.1

did a git clone
npm install
npm run dev

a new tab opens, and loads forever.

if I do npm start,
I can go to localhost:8000 and I see the todo app.

will test in linux as well.

**Comment by paOol** [comment]
no issues in linux

**Comment by tribou** [comment]
Hi @paOol, I haven't had a chance to test BrowserSync on Windows, so there could possibly be a misconfiguration somewhere.  Thanks for the report.

**Comment by yotamberk** [comment]
https://www.browsersync.io/docs#windows-users
